### PR TITLE
adding filter function

### PR DESCRIPTION
**Pull request by nuritizra**
adding a filter function to sources to filter out messages before saving to the db. (this will allow us to only send to alpha customers).
looking for a +1 so that we can deploy this version internally, but don't need this to be merged to master.

### CODE REVIEW

**Comment by jagheterfredrik** [comment]
Please re-open if this is still needed, I think the same can be achieved using hydrators?

**Comment by jagheterfredrik** [comment]
@nuritizra it'd be cool to have this documented in the main repo example; https://github.com/spotify/comet#example

**Comment by jagheterfredrik** [comment]
Could you also add tests?

**Comment by nuritizra** [comment]
hi, added filter documentation in the example, but I don't have permissions to merge:
https://github.com/spotify/comet/pull/4

**Pull request merged**
